apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-context7-backend.fullname" . }}
  labels:
    {{- include "open-context7-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if and .Values.qdrant.enabled .Values.service.exposeQdrant }}
    - port: {{ .Values.service.qdrantPort }}
      targetPort: qdrant
      protocol: TCP
      name: qdrant
    {{- end }}
  selector:
    {{- include "open-context7-backend.selectorLabels" . | nindent 4 }}
