#!/usr/bin/env sh
set -eu
export PYTHONDONTWRITEBYTECODE=1

find app tests \( -name '*.pyc' -o -name __pycache__ \) -print -delete >/dev/null 2>&1 || true

uv run ruff check app tests
uv run basedpyright app tests
uv run pytest -q -p no:cacheprovider
find app tests \( -name '*.pyc' -o -name __pycache__ \) -print -delete >/dev/null 2>&1 || true
if find app tests \( -name '*.pyc' -o -name __pycache__ \) -print | grep -q .; then
  printf '%s\n' 'generated bytecode artifacts found under app/ or tests' >&2
  exit 1
fi
printf '%s\n' 'CODE QUALITY APPROVED'
